CXXABI_1.3 {
  global:
    __cxa_allocate_exception;
    __cxa_begin_catch;
    __cxa_end_catch;
    __cxa_guard_abort;
    __cxa_guard_acquire;
    __cxa_guard_release;
    __cxa_pure_virtual;
    __cxa_rethrow;
    __cxa_throw;
    _ZTVN10__cxxabiv117__class_type_infoE;
    _ZTVN10__cxxabiv120__si_class_type_infoE;
};

CXXABI_1.3.2 {
  global:
    _ZTIN10__cxxabiv115__forced_unwindE;
};

CXXABI_1.3.3 {
  global:
    _ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE;
};

CXXABI_1.3.5 {
  global:
    _ZSt11_Hash_bytesPKvmm;
};

CXXABI_1.3.8 {
  global:
    __cxa_throw_bad_array_new_length;
};

CXXABI_1.3.9 {
  global:
    _ZdlPvm;
};

CXXABI_1.3.11 {
  global:
    __cxa_init_primary_exception;
};

GLIBCXX_3.4 {
  global:
    _ZNSt8ios_base4InitC1Ev;
    _Znam;
};

GLIBCXX_3.4.9 {
  global:
    _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l;
};

GLIBCXX_3.4.11 {
  global:
    _ZNSt6thread6detachEv;
};

GLIBCXX_3.4.14 {
  global:
    _ZTISt12future_error;
};

GLIBCXX_3.4.15 {
  global:
    _ZNSt8__detail15_List_node_base7_M_hookEPS0_;
};

GLIBCXX_3.4.17 {
  global:
    _ZNSt6thread20hardware_concurrencyEv;
};

GLIBCXX_3.4.18 {
  global:
    _ZNSt13random_device9_M_getvalEv;
};

GLIBCXX_3.4.19 {
  global:
    _ZNSt6chrono3_V212system_clock3nowEv;
};

GLIBCXX_3.4.20 {
  global:
    _ZSt24__throw_out_of_range_fmtPKcz;
};

GLIBCXX_3.4.21 {
  global:
    _ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE;
};

GLIBCXX_3.4.22 {
  global:
    _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE;
};
